# Generated by Django 5.1.6 on 2025-02-25 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='gig',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='employee',
        ),
        migrations.AddField(
            model_name='gig',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gigwork.user'),
        ),
        migrations.AddField(
            model_name='posting',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gigwork.user'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
