# Generated by Django 5.1.6 on 2025-02-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigwork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
