# Generated by Django 5.1.6 on 2025-05-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigwork', '0004_remove_gig_description_remove_gig_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='user',
            new_name='handler',
        ),
        migrations.RenameField(
            model_name='posting',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
